name: Flutter Web
on:
  push:
    branches:
      - master
permissions:
  contents: write
jobs:
  build:
    name: Build Web
    env:
      my_secret: $
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          version: 'latest'
      - run: flutter config --enable-web
      - run: flutter pub get
      - run: flutter build web --release --base-href "/streetlamp/"

      - name: Deploy to GitHub Pages
        run: |
          git clone --branch gh-pages https://github.com/hyooosong/streetlamp.git gh-pages
          rm -rf gh-pages/*
          cp -r build/web/* gh-pages/
          cd gh-pages
          git add .
          git commit -m "Deploy to GitHub Pages"
          git push origin gh-pages