name: Flutter Web
on:
  push:
    branches:
      - master
permissions:
  contents: write
jobs:
  build:
    name: Build Web
    env:
      my_secret: $
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          version: 3.7.0
      - run: flutter config --enable-web
      - run: flutter pub get
      - run: flutter build web --release
        working-directory: /home/runner/work/streetlamp/streetlamp
      - run: |
          cd /home/runner/work/streetlamp/streetlamp/build/web
          git checkout -b gh-pages
          git push origin gh-pages -f