name: Flutter Web
on:
  push:
    branches:
      - master
permissions:
  contents: write
jobs:
  build:
    name: Build Web
    env:
      my_secret: $
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          version: 'latest'
      - run: flutter config --enable-web
      - run: flutter pub get
      - run: flutter build web --release
        working-directory: /home/runner/work/streetlamp/streetlamp
      - run: |
          git clone https://github.com/hyooosong/streetlamp.io.git
          cd /home/runner/work/streetlamp/streetlamp/streetlamp.io
          git config --global user.email gythd1998@gmail.com
          git config --global user.name hyooosong
          git add .
          git commit -m "Deploy"
          git branch -M main
          git push -u origin main