name: Flutter Web
on:
  push:
    branches:
      - master
permissions:
  contents: write
jobs:
  build:
    name: Build Web
    env:
      my_secret: $
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          version: 'latest'
      - run: flutter config --enable-web
      - run: flutter pub get
      - run: flutter build web --release --base-href "/streetlamp/"
        working-directory: /home/runner/work/streetlamp/streetlamp
      - run: |
          cd /home/runner/work/streetlamp/streetlamp/build/web
          git init
          git config --global user.email gythd1998@gmail.com
          git config --global user.name hyooosong
          git fetch origin gh-pages  # 원격 gh-pages 브랜치를 가져옴
          git checkout gh-pages || git checkout -b gh-pages  # 존재하지 않으면 새로 생성
          git add .
          git commit -m "Deploy to GitHub Pages"
          git push origin gh-pages --force